version: '3'
services:
  db:
    image: mongo
    volumes:
      - rmongo:/data/db
  server:
    build:
      context: ./
      dockerfile: server.dockerfile
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017
  frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    ports:
      - 80:80
    depends_on:
      - server
volumes:
  rmongo:
